language: node_js
node_js:
  - "0.10"
  - "0.12"
before_script: "npm install -g codeclimate-test-reporter"
script: "make test-cov"
after_script: "cat coverage/lcov.info | codeclimate"
addons:
  code_climate:
    repo_token: 24a4c47918bae008a97ac96b8a4c3f16ca4bc684480f95f802b6ff5429953ab9
